apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-docker
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flask-docker
  template:
    metadata:
      labels:
        app: flask-docker
    spec:
      containers:
      - image: docker.io/nightmar39/basic-flask-docker@sha256:a9644ba66b498cf0d7f5235918f788d888cd059483a3c4d2071242
        name: flask-docker
        ports:
        - containerPort: 5000
